# name: testing github workflow
# on: [pull_request]
# jobs:
#   Coba-Github-Workflow:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "CI step go go go"
  
#   ini-unit-test:
#     runs-on: ubuntu-latest
#     steps:
#        - uses: actions/checkout@v3

#        - name: Setup go
#          uses: actions/setup-go@v3
#          with:
#            go-version: '1.18'

#        - run: go test -v ./...

#   deploy:
#     needs: [ini-unit-test]

#     runs-on: ubuntu-latest

#     steps:
#     - name: 'SSH to Server'
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.HOST }}
#         username: ${{ secrets.USERNAME }}
#         password: ${{ secrets.PASSWORD }}
#         port: ${{ secrets.PORT }}
#         script: |
#           cd aplikasi/invoiceinaja-backend
#           git pull origin main

          
# # sudo kill $(sudo lsof -t -i:8080)